import { StyleSheet } from 'react-native';

export const UseMemoStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0B0C10',
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 8,
    marginTop: 20,
  },
  subtitle: {
    fontSize: 16,
    color: '#C5C6C7',
    textAlign: 'center',
    marginBottom: 24,
  },
  controlsContainer: {
    backgroundColor: '#1F2833',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
  },
  searchInput: {
    backgroundColor: '#0B0C10',
    borderWidth: 1,
    borderColor: '#45A29E',
    borderRadius: 8,
    padding: 12,
    color: '#FFFFFF',
    marginBottom: 12,
    fontSize: 16,
  },
  departmentFilter: {
    marginTop: 8,
  },
  filterTitle: {
    fontSize: 14,
    color: '#C5C6C7',
    marginBottom: 8,
  },
  filterButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterButton: {
    backgroundColor: '#2D3748',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#45A29E',
  },
  filterButtonActive: {
    backgroundColor: '#45A29E',
  },
  filterButtonText: {
    color: '#C5C6C7',
    fontSize: 12,
    fontWeight: '500',
  },
  filterButtonTextActive: {
    color: '#0B0C10',
    fontWeight: '600',
  },
  statsContainer: {
    backgroundColor: '#1F2833',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: '#66FCF1',
  },
  statsTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#66FCF1',
    marginBottom: 8,
  },
  statsText: {
    fontSize: 14,
    color: '#C5C6C7',
    marginBottom: 4,
  },
  addUserContainer: {
    backgroundColor: '#1F2833',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  addUserInput: {
    flex: 1,
    backgroundColor: '#0B0C10',
    borderWidth: 1,
    borderColor: '#45A29E',
    borderRadius: 8,
    padding: 12,
    color: '#FFFFFF',
    fontSize: 14,
  },
  addUserButton: {
    backgroundColor: '#45A29E',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
  },
  addUserButtonDisabled: {
    backgroundColor: '#2D3748',
    opacity: 0.5,
  },
  addUserButtonText: {
    color: '#0B0C10',
    fontWeight: '600',
    fontSize: 14,
  },
  listContainer: {
    backgroundColor: '#1F2833',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  listTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#66FCF1',
    marginBottom: 12,
  },
  list: {
    flex: 1,
  },
  userCard: {
    backgroundColor: '#0B0C10',
    padding: 16,
    borderRadius: 8,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#45A29E',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  userDetails: {
    fontSize: 14,
    color: '#C5C6C7',
    marginBottom: 2,
  },
  userActions: {
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    padding: 8,
    borderRadius: 6,
    minWidth: 36,
    alignItems: 'center',
  },
  editButton: {
    backgroundColor: '#45A29E',
  },
  deleteButton: {
    backgroundColor: '#f97a9cff',
  },
  actionButtonText: {
    fontSize: 14,
  },
  emptyText: {
    textAlign: 'center',
    color: '#C5C6C7',
    fontSize: 16,
    marginTop: 20,
    fontStyle: 'italic',
  },
  navigationButtons: {
    gap: 12,
    marginBottom: 20,
  },
  navButton: {
    backgroundColor: '#2D3748',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#45A29E',
  },
  navButtonText: {
    color: '#66FCF1',
    fontWeight: '600',
    fontSize: 14,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#1F2833',
    borderRadius: 12,
    padding: 24,
    width: '100%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 20,
  },
  modalInput: {
    backgroundColor: '#0B0C10',
    borderWidth: 1,
    borderColor: '#45A29E',
    borderRadius: 8,
    padding: 12,
    color: '#FFFFFF',
    marginBottom: 16,
    fontSize: 16,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  modalButton: {
    flex: 1,
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#2D3748',
    borderWidth: 1,
    borderColor: '#45A29E',
  },
  saveButton: {
    backgroundColor: '#45A29E',
  },
  cancelButtonText: {
    color: '#C5C6C7',
    fontWeight: '600',
    fontSize: 16,
  },
  saveButtonText: {
    color: '#0B0C10',
    fontWeight: '600',
    fontSize: 16,
  },
});